### ISSUE TITLE
Error: Cannot find module 'tslint'

### ISSUE THREAD

**Issue by TitaneBoy** [angular/material-prefix-updater#10]
Hi team.. When running the material-prefix-updater (with `mat-switcher -p ./tsconfig.json`), I got the following error:

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'tslint'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.resolve (internal/module.js:18:19)
    at sync (C:\Users\MyUser\AppData\Local\Yarn\config\global\node_modules\resolve-bin\index.js:60:21)
    at Object.findTslintBinaryPath (C:\Users\MyUser\AppData\Local\Yarn\config\global\node_modules\angular-material-prefix-updater\tslint\find-tslint-binary.js:10:24)
    at migrateProject (C:\Users\MyUser\AppData\Local\Yarn\config\global\node_modules\angular-material-prefix-updater\cli.js:62:42)
    at Object.<anonymous> (C:\Users\MyUser\AppData\Local\Yarn\config\global\node_modules\angular-material-prefix-updater\cli.js:58:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

Everything is up to date in my modules...

Here is my package.json file:

```
{
  "name": "mywebclient",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.4.3",
    "@angular/cdk": "2.0.0-beta.11",
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/flex-layout": "2.0.0-beta.9",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/material": "2.0.0-beta.11",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@angular/router": "4.4.3",
    "bootstrap": "4.0.0-beta",
    "core-js": "2.5.1",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "material-design-icons": "3.0.1",
    "rxjs": "5.4.3",
    "zone.js": "0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "1.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/language-service": "4.4.3",
    "@types/jasmine": "2.6.0",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.0.31",
    "codelyzer": "3.2.0",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-firefox-launcher": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-json-reporter": "1.2.0",
    "protractor": "5.1.2",
    "ts-node": "3.3.0",
    "tslint": "5.7.0",
    "typescript": "2.5.3"
  }
}
```

Can you help me, please ?

Thank you

**Comment by DevVersion** [comment]
Sorry for the late response. I'm not really sure why this happens. Maybe the tool has not been installed properly. Can you retry installing the tool globally?
