### ISSUE TITLE
Error running material prefix updater ComponentWalker

### ISSUE THREAD

**Issue by aciccarello** [angular/material-prefix-updater#16]
When running the prefix updater, the program accepts my tsconfig file and begins to migrate the application. However, part way through it throws an error with no indication of the file which is causing the problem.

Looks like most of the migration worked, though there are still `md-` typography classes in the html of my components.

## Stacktrace
```
$ npx -p angular-material-prefix-updater mat-switcher --project tsconfig.json
npx: installed 117 in 93.452s

TypeError: Cannot read property 'length' of undefined
    at SwitchTemplatesWalker.ComponentWalker._visitDirectiveCallExpression (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\tslint\comp
onent-walker.js:47:68)
    at SwitchTemplatesWalker.ComponentWalker.visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\tslint\component-walker.js:40:2
2)
    at C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11902:24)
    at Object.forEachChild (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:12154:24)
    at SwitchTemplatesWalker.SyntaxWalker.walkChildren (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\languag
e\walker\syntaxWalker.js:535:12)
    at SwitchTemplatesWalker.SyntaxWalker.visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\w
alker\syntaxWalker.js:530:22)
    at SwitchTemplatesWalker.ComponentWalker.visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\tslint\component-walker.js:43:3
6)
    at C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNodes (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11911:30)
TypeError: Cannot read property 'length' of undefined
    at SwitchStylesheetsWalker.ComponentWalker._visitDirectiveCallExpression (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\tslint\co
mponent-walker.js:47:68)
    at SwitchStylesheetsWalker.ComponentWalker.visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\tslint\component-walker.js:40
:22)
    at C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11902:24)
    at Object.forEachChild (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:12154:24)
    at SwitchStylesheetsWalker.SyntaxWalker.walkChildren (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\langu
age\walker\syntaxWalker.js:535:12)
    at SwitchStylesheetsWalker.SyntaxWalker.visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language
\walker\syntaxWalker.js:530:22)
    at SwitchStylesheetsWalker.ComponentWalker.visitNode (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\tslint\component-walker.js:43
:36)
    at C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNodes (C:\Users\Username\AppData\Roaming\npm-cache\_npx\13156\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11911:30)

Make sure the following things are done correctly:
 • Angular Material is installed in the project (for type checking)
 • Project "tsconfig.json" configuration matches the desired files.

× Errors occurred while migrating the Angular Material project.
```

## Environment
Node: v6.11.2
npm: 5.4.1
OS: Windows 7 64-bit

**Comment by DevVersion** [comment]
This has been fixed with v0.0.6
