### ISSUE TITLE
Errors occurred while migrating the Angular Material project.

### ISSUE THREAD

**Issue by matte00** [angular/material-prefix-updater#7]
I have same issues with this tool. I did:

mat-switcher -p tsconfig.json --extra-css 'src/**/*.scss'
 
TypeError: Cannot read property 'valueDeclaration' of undefined
    at SwitchIdentifiersWalker.visitIdentifier (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\rules\switchIdentifiersRule.js:70:66)
    at SwitchIdentifiersWalker.SyntaxWalker.visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:386:22)
    at C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11900:24)
    at Object.forEachChild (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11936:21)
    at SwitchIdentifiersWalker.SyntaxWalker.walkChildren (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at SwitchIdentifiersWalker.SyntaxWalker.visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:530:22)
    at C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11900:24)
    at Object.forEachChild (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11994:24)
TypeError: Cannot read property 'valueDeclaration' of undefined
    at SwitchIdentifiersWalker.visitIdentifier (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\rules\switchIdentifiersRule.js:70:66)
    at SwitchIdentifiersWalker.SyntaxWalker.visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:386:22)
    at C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11900:24)
    at Object.forEachChild (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:12032:21)
    at SwitchIdentifiersWalker.SyntaxWalker.walkChildren (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at SwitchIdentifiersWalker.SyntaxWalker.visitPropertyAccessExpression (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:207:14)
    at SwitchIdentifiersWalker.SyntaxWalker.visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:461:22)
    at C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\Users\mgasperini\AppData\Roaming\npm\node_modules\angular-material-prefix-updater\node_modules\typescript\lib\typescript.js:11900:24)

Make sure the following things are done correctly:
 • Angular Material is installed in the project (for type checking)
 • Project "tsconfig.json" configuration matches the desired files.

**Comment by mreu** [comment]
I have the same error. I called mat-switcher -p tsconfig.json

TypeError: Cannot read property 'valueDeclaration' of undefined
    at SwitchIdentifiersWalker.visitIdentifier (/usr/local/lib/node_modules/angular-material-prefix-updater/rules/switchIdentifiersRule.js:70:66)
    at SwitchIdentifiersWalker.SyntaxWalker.visitNode (/usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/tslint/lib/language/walker/syntaxWalker.js:386:22)
    at /usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/typescript/lib/typescript.js:11909:30)
    at Object.forEachChild (/usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/typescript/lib/typescript.js:12040:21)
    at SwitchIdentifiersWalker.SyntaxWalker.walkChildren (/usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchIdentifiersWalker.SyntaxWalker.visitCallExpression (/usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/tslint/lib/language/walker/syntaxWalker.js:54:14)
    at SwitchIdentifiersWalker.SyntaxWalker.visitNode (/usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/tslint/lib/language/walker/syntaxWalker.js:305:22)
    at /usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/usr/local/lib/node_modules/angular-material-prefix-updater/node_modules/typescript/lib/typescript.js:11900:24)

Make sure the following things are done correctly:
 • Angular Material is installed in the project (for type checking)
 • Project "tsconfig.json" configuration matches the desired files.

✖ Errors occurred while migrating the Angular Material project.

**Comment by munjalpandya** [comment]
Getting below scripting error after running the update tool

Error: (SystemJS) expected expression, got '<'
	@http://localhost:54202/app/app.module.js:13:18
	@http://localhost:54202/app/app.module.js:1:31
	@http://localhost:54202/app/app.module.js:1:2
	@http://localhost:54202/app/main.js:4:20
	@http://localhost:54202/app/main.js:1:31
	@http://localhost:54202/app/main.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:54202/node_modules/zone.js/dist/zone.js:365:17
	Zone.prototype.run@http://localhost:54202/node_modules/zone.js/dist/zone.js:125:24
	scheduleResolveOrReject/<@http://localhost:54202/node_modules/zone.js/dist/zone.js:760:52
	ZoneDelegate.prototype.invokeTask@http://localhost:54202/node_modules/zone.js/dist/zone.js:398:17
	Zone.prototype.runTask@http://localhost:54202/node_modules/zone.js/dist/zone.js:165:28
	drainMicroTaskQueue@http://localhost:54202/node_modules/zone.js/dist/zone.js:593:25
	ZoneTask/this.invoke@http://localhost:54202/node_modules/zone.js/dist/zone.js:464:25
	
	Evaluating http://localhost:54202/node_modules/@angular/cdk/bundles/cdk.umd.js/stepper
	Evaluating http://localhost:54202/app/app.module.js
	Evaluating http://localhost:54202/app/main.js
	Error loading http://localhost:54202/app/main.js
Stack trace:
(SystemJS) expected expression, got '<'
	@http://localhost:54202/app/app.module.js:13:18
	@http://localhost:54202/app/app.module.js:1:31
	@http://localhost:54202/app/app.module.js:1:2
	@http://localhost:54202/app/main.js:4:20
	@http://localhost:54202/app/main.js:1:31
	@http://localhost:54202/app/main.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:54202/node_modules/zone.js/dist/zone.js:365:17
	Zone.prototype.run@http://localhost:54202/node_modules/zone.js/dist/zone.js:125:24
	scheduleResolveOrReject/<@http://localhost:54202/node_modules/zone.js/dist/zone.js:760:52
	ZoneDelegate.prototype.invokeTask@http://localhost:54202/node_modules/zone.js/dist/zone.js:398:17
	Zone.prototype.runTask@http://localhost:54202/node_modules/zone.js/dist/zone.js:165:28
	drainMicroTaskQueue@http://localhost:54202/node_modules/zone.js/dist/zone.js:593:25
	ZoneTask/this.invoke@http://localhost:54202/node_modules/zone.js/dist/zone.js:464:25
	
	Evaluating http://localhost:54202/node_modules/@angular/cdk/bundles/cdk.umd.js/stepper
	Evaluating http://localhost:54202/app/app.module.js
	Evaluating http://localhost:54202/app/main.js
	Error loading http://localhost:54202/app/main.js

**Comment by DevVersion** [comment]
@munjalpandya This seems not to be caused by the `mat-switcher`. Your app just doesn't have the proper SystemJS mappings set. 

e.g.

```ts
map: {
  '@angular/cdk/stepper': 'node_modules/@angular/cdk/bundles/cdk-stepper.umd.js'
}
````

**Comment by DevVersion** [comment]
@matte00 @mreu Can you guys please retry with `0.0.5` of the tool?

**Comment by munjalpandya** [comment]
@DevVersion below is my SystemJS. Can you check what is missing / wrong?

`/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
            '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js',
              '@angular/cdk/a11y': 'npm:@angular/cdk/bundles/cdk-a11y.umd.js',
              '@angular/cdk/bidi': 'npm:@angular/cdk/bundles/cdk-bidi.umd.js',
              '@angular/cdk/coercion': 'npm:@angular/cdk/bundles/cdk-coercion.umd.js',
              '@angular/cdk/collections': 'npm:@angular/cdk/bundles/cdk-collections.umd.js',
              '@angular/cdk/keycodes': 'npm:@angular/cdk/bundles/cdk-keycodes.umd.js',
              '@angular/cdk/observers': 'npm:@angular/cdk/bundles/cdk-observers.umd.js',
              '@angular/cdk/overlay': 'npm:@angular/cdk/bundles/cdk-overlay.umd.js',
              '@angular/cdk/platform': 'npm:@angular/cdk/bundles/cdk-platform.umd.js',
              '@angular/cdk/portal': 'npm:@angular/cdk/bundles/cdk-portal.umd.js',
              '@angular/cdk/rxjs': 'npm:@angular/cdk/bundles/cdk-rxjs.umd.js',
              '@angular/cdk/table': 'npm:@angular/cdk/bundles/cdk-table.umd.js',
              '@angular/cdk/scrolling': 'npm:@angular/cdk/bundles/cdk-scrolling.umd.js',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: 'main.js', defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            }
        }
    });
})(this);`

**Comment by mreu** [comment]
@DevVersion: It would be nice if the tool would log which file is changed now. I have done this with a local copy of the tool and find the file where the exception happens and made the changes by hand. Then I can rerun the tool and it works through all files.

**Comment by maratnek** [comment]
Hi. I have the same error but I'm using angular-cli. How Can I change to everything work?

**Comment by DevVersion** [comment]
This has been fixed v0.0.5 of the tool. Also there is **v0.0.6** now.

**Comment by alirezamirian** [comment]
Getting the same error in v0.0.6
It would be nice to have at least the log of the occurred the error.

**Comment by Yakamozduan** [comment]
I have the same error !
plz fix it!
